AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: python3.12
      CodeUri: src/
      MemorySize: 1024
      Timeout: 900

      Environment:
        Variables:
          GH_PAT: ""
          PROJECTS_TABLE: "eezy-ml-projects"

      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ec2:RunInstances
                - ec2:DescribeInstances
                - ec2:TerminateInstances
                - ec2:CreateSecurityGroup
                - ec2:AuthorizeSecurityGroupIngress
                - ec2:DescribeSecurityGroups
                - ec2:DescribeVpcs
                - ec2:DescribeSubnets
                - ec2:CreateTags
              Resource: '*'
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: '*'
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:DeleteItem
                - dynamodb:UpdateItem
                - dynamodb:Scan
              Resource:
                - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/eezy-ml-projects

      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
